apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-work-app
  namespace: argocd
spec:
  destination:
    namespace: work
    server: https://kubernetes.default.svc 
  project: work 
  source: 
    path: overlays/work
    repoURL: https://github.com/deluis85/argocd-test
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
